[project]
name = "hello-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.3.2",
    "polars>=1.35.2",
    "requests>=2.32.4",
    "selenium>=4.34.2",
]
